definitions:
  caches:
    nextcache: .next/cache
pipelines:
  custom:
    default:
      - step:
          name: Build
          image: node:14.16.0
          caches:
            - node
            - nextcache
          script:
            - yarn install
            - yarn build