definitions:
  caches:
    nextcache: .next/cache
    bundler: vendor/bundle
pipelines:
  pull-requests:
    "**":
      - step:
          name: Build
          image: node:14.16.0
          caches:
            - node
            - nextcache
          script:
            - yarn install
            - yarn test
            - yarn build
  custom:
    default:
      - step:
          name: Test and Build
          image: node:14.16.0
          caches:
            - node
            - nextcache
          script:
            - yarn install
            - yarn test
            - yarn build
    "Deploy to staging from GITHUB develop":
      - step:
          name: Deploy To Staging
          image: ruby:2.6.3
          deployment: staging
          caches:
            - bundler
          script:
            - gem install bundler
            - bundle install
            - bundle exec cap staging deploy
    "Deploy to production from GITHUB main":
      - step:
          name: Deploy To Production
          image: ruby:2.6.3
          deployment: production
          caches:
            - bundler
          script:
            - gem install bundler
            - bundle install
            - bundle exec cap production deploy
