export const biodiversityTopics = [
  "Wildlife",
  "Animals",
  "Biodiversity",
  "Endangered Species",
  "Wildlife Conservation",
  "Wildlife Trafficking",
  "Extinction",
  "Critically Endangered Species",
  "Saving Species From Extinction",
  "Biodiversity Crisis",
  "New Species",
  "Species Discovery",
  "Climate Change And Biodiversity",
  "Amazon Biodiversity",
  "Mass Extinction",
  "Invasive Species",
  "Wildlife Corridors",
  "Biodiversity And Medicine",
  "Palm Oil And Biodiversity",
  "Amphibian Crisis",
  "Redd And Biodiversity"
];
