export const climateTopics = [
  "Climate Change",
  "Impact Of Climate Change",
  "Carbon Emissions",
  "Global Warming",
  "Greenhouse Gas Emissions",
  "Climate Change And Forests",
  "Climate",
  "Climate Science",
  "Oceans And Climate Change",
  "Climate Change And Extreme Weather",
  "Fossil Fuels",
  "Climate Change And Conservation",
  "Adaptation To Climate Change",
  "Global Warming Mitigation",
  "Climate Change Politics",
  "Air Pollution",
  "Carbon Dioxide",
  "Climate Change Policy",
  "Climate Change And Extinction",
  "Emission Reduction",
  "Climate Activism",
  "Climate Change And Food",
  "climate policy",
  "Climate Modeling",
  "Temperatures",
  "Sea Ice",
  "Carbon Footprint",
  "Extinction And Climate Change",
  "greenhouse gases",
  "Climate Politics",
  "Mitigation",
  "climate finance",
  "Methane",
  "Heatwave",
  "Climate Change Denial"
];