export const forestsTopics = [
  "Forests",
  "Rainforests",
  "Deforestation",
  "Tropical Forests",
  "Rainforest Destruction",
  "Rainforest Deforestation",
  "Tropical Deforestation",
  "Threats To Rainforests",
  "Amazon Destruction",
  "Threats To The Amazon",
  "Forest Fires",
  "Logging",
  "Drivers Of Deforestation",
  "Forest Destruction",
  "Illegal Logging",
  "Forestry",
  "Saving The Amazon",
  "Forest Loss",
  "Forest People",
  "Amazon Rainforest",
  "Rainforest Conservation",
  "Saving Rainforests",
  "Wildfires",
  "Primary Forests",
  "Rainforest Logging",
  "Timber",
  "Old Growth Forests",
  "Rainforest People",
  "forest degradation",
  "Forest Carbon",
  "Amazon Logging",
  "Illegal Timber Trade",
  "Forest Fragmentation",
  "Community Forests",
  "Sustainable Forest Management",
  "Reforestation",
  "Agroforestry",
  "Trees",
  "Dry Forests",
  "Amazon fire beat",
  "Community Forestry",
  "Zero Deforestation Commitments",
  "timber trade",
  "Timber Laws",
  "Rainforest Biodiversity",
  "Avoided Deforestation",
  "Rainforest Agriculture",
  "Temperate Forests",
  "Redd",
  "Forest Products",
  "logging roads",
  "Forest Regeneration",
  "Afforestation",
  "Forest Elephants",
  "Selective Logging",
  "Secondary Forests",
  "Food Vs Forests Debate",
  "Atlantic Forest",
  "Forest Recovery",
  "Forest Stewardship Council",
  "boreal forests",
  "China Logging",
  "Reduced Impact Logging",
  "Empty Forests",
  "biologging"
];
