export const oceanTopics = [
  "Oceans",
  "Marine Conservation",
  "Marine Ecosystems",
  "Fisheries",
  "Marine",
  "Fish",
  "Fishing",
  "Marine Biodiversity",
  "Marine Animals",
  "Overfishing",
  "Illegal Fishing",
  "Marine Protected Areas",
  "Marine Crisis",
  "Coral Reefs",
  "Marine Mammals",
  "Coastal Ecosystems",
  "Ocean Crisis",
  "Sea Turtles",
  "Shark finning",
  "Climate Change And Coral Reefs",
  "Coral Bleaching",
  "Deep Sea",
  "Ocean Warming",
  "Deep Sea Mining",
  "Great Barrier Reef",
  "Marine Birds",
  "Gillnets",
  "Sea Levels",
  "Bycatch",
  "Ocean Acidification"
];
